-- AlterTable
ALTER TABLE `rentedcar` ADD COLUMN `status` ENUM('VERIFIED', 'IN_PROGRESS', 'NOT_VERIFIED', 'BLOCKED') NOT NULL DEFAULT 'IN_PROGRESS';

-- AlterTable
ALTER TABLE `reservedcar` ADD COLUMN `status` ENUM('VERIFIED', 'IN_PROGRESS', 'NOT_VERIFIED', 'BLOCKED') NOT NULL DEFAULT 'IN_PROGRESS';
