-- AlterTable
ALTER TABLE `car` MODIFY `status` ENUM('VERIFIED', 'IN_PROGRESS', 'NOT_VERIFIED', 'BLOCKED', 'COMPLETED', 'RENTED') NOT NULL DEFAULT 'NOT_VERIFIED';

-- AlterTable
ALTER TABLE `client` MODIFY `status` ENUM('VERIFIED', 'IN_PROGRESS', 'NOT_VERIFIED', 'BLOCKED', 'COMPLETED', 'RENTED') NOT NULL DEFAULT 'NOT_VERIFIED';

-- AlterTable
ALTER TABLE `rental` MODIFY `status` ENUM('VERIFIED', 'IN_PROGRESS', 'NOT_VERIFIED', 'BLOCKED', 'COMPLETED', 'RENTED') NOT NULL DEFAULT 'NOT_VERIFIED';

-- AlterTable
ALTER TABLE `rentedcar` MODIFY `status` ENUM('VERIFIED', 'IN_PROGRESS', 'NOT_VERIFIED', 'BLOCKED', 'COMPLETED', 'RENTED') NOT NULL DEFAULT 'IN_PROGRESS';

-- AlterTable
ALTER TABLE `reservedcar` MODIFY `status` ENUM('VERIFIED', 'IN_PROGRESS', 'NOT_VERIFIED', 'BLOCKED', 'COMPLETED', 'RENTED') NOT NULL DEFAULT 'IN_PROGRESS';
